name: new01
description: "A new Flutter project combining features from two configurations."
publish_to: 'none' # Keep this line if you're not publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.3.0
  speech_to_text: ^7.0.0

  photo_view: ^0.14.0
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  table_calendar: ^3.2.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  package_info_plus: ^8.2.1
  url_launcher: ^6.3.1
  google_sign_in: ^6.2.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pie_chart: ^5.0.0
  glassmorphism: ^3.0.0
  image_picker: ^1.0.0
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3
  flutter_svg: ^2.0.17
  intl: ^0.20.0
  sign_in_with_apple: ^6.1.4
  flutter_facebook_auth: ^7.1.1
  flutter_staggered_animations: ^1.1.1
  confetti: ^0.7.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  hive_generator: ^1.1.0
  build_runner: ^2.3.3
  fl_chart: ^0.45.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/Lottie/

  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: GrandHotel
      fonts:
        - asset: fonts/GrandHotel-Regular.ttf
    - family: Impact
      fonts:
        - asset: fonts/Impact.ttf
